# fly.toml app configuration file generated for nextjs-demo on 2023-05-27T15:24:13+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nextjs-demo"
primary_region = "otp"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
